In [149]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [150]:
tokenizer = Tokenizer()

In [151]:
data = """# 1. Basic arithmetic operations
x = 5
y = 3
sum = x + y  # Addition
difference = x - y  # Subtraction
product = x * y  # Multiplication
quotient = x / y  # Division
remainder = x % y  # Modulus (remainder after division)
power = x ** y  # Exponentiation
floor_division = x // y  # Floor division
print("Sum:", sum)
print("Difference:", difference)
print("Product:", product)
print("Quotient:", quotient)
print("Remainder:", remainder)
print("Power:", power)
print("Floor Division:", floor_division)

# 2. Conditional statements (if-else)
age = 25
if age >= 18:
    print("You are an adult.")
    if age >= 65:
        print("You are a senior citizen.")
else:
    print("You are a minor.")

# 3. Loops (for loop)
for i in range(5):
    print(i)  # Prints numbers from 0 to 4

for char in "Python":
    print(char)  # Prints each character of the string

# Using range with step
for i in range(0, 10, 2):
    print(i)  # Prints even numbers from 0 to 8

# 4. Functions
def greet(name):
    print("Hello,", name + "!")

def add(a, b):
    return a + b

def is_even(number):
    return number % 2 == 0

def factorial_recursive(n):
    if n == 1 or n == 0:
        return 1
    else:
        return n * factorial_recursive(n - 1)

def reverse_string(s):
    return s[::-1]

print(greet("Alice"))  # Output: Hello, Alice!
print(add(5, 3))  # Output: 8
print(is_even(10))  # Output: True
print(factorial_recursive(5))  # Output: 120
print(reverse_string("Python"))  # Output: nohtyP

# 5. Lists
fruits = ["apple", "banana", "orange"]
fruits.insert(1, "cherry")  # Insert cherry at position 1
fruits.remove("banana")  # Remove banana from the list
sorted_fruits = sorted(fruits)  # Sort the list
print(sorted_fruits)

# Using list comprehension
squares = [x**2 for x in range(10)]
print(squares)  # Output: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# Iterating with indices
for index, fruit in enumerate(fruits):
    print(f"Fruit {index + 1}: {fruit}")

# 6. Dictionaries
student = {"name": "John", "age": 20, "major": "Computer Science"}
student["graduated"] = False  # Add a new key-value pair
student["age"] += 1  # Update age
for key, value in student.items():
    print(f"{key}: {value}")

# 7. Working with files
try:
    with open("my_file.txt", "r") as file:
        content = file.read()
        print(content)
except FileNotFoundError:
    print("File not found.")

# Appending to a file
with open("my_file.txt", "a") as file:
    file.write("New line added.\n")

# 8. Classes and objects (basic example)
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def bark(self):
        print("Woof!")

    def get_human_years(self):
        return self.age * 7

my_dog = Dog("Buddy", 3)
print(my_dog.name)
my_dog.bark()  # Output: Woof!
print(f"{my_dog.name} is {my_dog.get_human_years()} human years old.")

# 9. Using external libraries
import math
result = math.sqrt(25)  # Calculate the square root of 25
print(result)

# Calculating sine and cosine
angle = math.radians(30)
print("Sine:", math.sin(angle))
print("Cosine:", math.cos(angle))

# 10. Nested loops
for x in range(1, 4):
    for y in range(1, 4):
        print(f"{x} * {y} = {x * y}")
    print("End of row")

# 11. While loop
count = 0
while count < 5:
    print(f"Count is {count}")
    count += 1

# Infinite loop with break
while True:
    print("This runs once")
    break

# 12. Recursive function
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

print([fibonacci(i) for i in range(10)])  # First 10 Fibonacci numbers

# 13. List comprehension with condition
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [x for x in numbers if x % 2 == 0]
print(even_numbers)

# 14. Lambda function with map
names = ["Alice", "Bob", "Charlie"]
uppercase_names = list(map(lambda x: x.upper(), names))
print(uppercase_names)

"""


In [152]:
tokenizer.fit_on_texts([data])

In [153]:
input_sequences = []

In [154]:
for line in data.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range (1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [155]:
input_sequences

[[3, 75],
 [3, 75, 110],
 [3, 75, 110, 111],
 [2, 15],
 [4, 30],
 [47, 2],
 [47, 2, 4],
 [47, 2, 4, 112],
 [48, 2],
 [48, 2, 4],
 [48, 2, 4, 113],
 [49, 2],
 [49, 2, 4],
 [49, 2, 4, 114],
 [50, 2],
 [50, 2, 4],
 [50, 2, 4, 25],
 [37, 2],
 [37, 2, 4],
 [37, 2, 4, 115],
 [37, 2, 4, 115, 37],
 [37, 2, 4, 115, 37, 116],
 [37, 2, 4, 115, 37, 116, 25],
 [51, 2],
 [51, 2, 4],
 [51, 2, 4, 117],
 [38, 25],
 [38, 25, 2],
 [38, 25, 2, 4],
 [38, 25, 2, 4, 38],
 [38, 25, 2, 4, 38, 25],
 [1, 47],
 [1, 47, 47],
 [1, 48],
 [1, 48, 48],
 [1, 49],
 [1, 49, 49],
 [1, 50],
 [1, 50, 50],
 [1, 37],
 [1, 37, 37],
 [1, 51],
 [1, 51, 51],
 [1, 38],
 [1, 38, 25],
 [1, 38, 25, 38],
 [1, 38, 25, 38, 25],
 [16, 118],
 [16, 118, 119],
 [16, 118, 119, 26],
 [16, 118, 119, 26, 39],
 [6, 40],
 [26, 6],
 [26, 6, 120],
 [1, 52],
 [1, 52, 53],
 [1, 52, 53, 121],
 [1, 52, 53, 121, 122],
 [26, 6],
 [26, 6, 123],
 [1, 52],
 [1, 52, 53],
 [1, 52, 53, 17],
 [1, 52, 53, 17, 124],
 [1, 52, 53, 17, 124, 125],
 [1, 52],
 [1, 52, 

In [156]:
max_lenghth = 0
for i in range(len(input_sequences)):
    if len(input_sequences[i]) > max_lenghth:
        max_lenghth = len(input_sequences[i])
print(max_lenghth)

14


In [157]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
input_sequences = pad_sequences(input_sequences, maxlen=max_lenghth, padding='pre')
print(input_sequences)

[[  0   0   0 ...   0   3  75]
 [  0   0   0 ...   3  75 110]
 [  0   0   0 ...  75 110 111]
 ...
 [  0   0   0 ...   2 206  46]
 [  0   0   0 ...   0   1 109]
 [  0   0   0 ...   1 109  46]]


In [158]:
x = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [159]:
x

y

array([ 75, 110, 111,  15,  30,   2,   4, 112,   2,   4, 113,   2,   4,
       114,   2,   4,  25,   2,   4, 115,  37, 116,  25,   2,   4, 117,
        25,   2,   4,  38,  25,  47,  47,  48,  48,  49,  49,  50,  50,
        37,  37,  51,  51,  38,  25,  38,  25, 118, 119,  26,  39,  40,
         6, 120,  52,  53, 121, 122,   6, 123,  52,  53,  17, 124, 125,
        52,  53,  17, 126,  76,   5,  54,  27,   7,  18,  15,  27,  55,
        19,  56,  10,  57,  28,  77,   7,  78,  77,  55, 127, 128,  58,
        41,  59,  18,  11, 129,  27,   7,  18,  10,  20,  16,  27,  55,
        31,  19,  56,  10,  57,  42, 130,  79,  12,  80,  12,  61,  17,
        81,  17,  81,  43,  31,  82,  82,  16,  10,  62,  44,   8,   8,
         3, 131,   8,  10,   3,   8,  62,  44,   8,   3,  83,  59,  84,
        84,   3,  79,  63,  21,  80,  63,  61,  15,  30,  21,  42,  43,
        31,  20,  21,  85,  62,  44,  15,  21, 132,  83,  59,  78,  21,
       133, 134, 135,  64, 136,  86,   3,  87,  86,  87, 137, 13

In [160]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [161]:
from ast import mod
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=10))
model.add(LSTM(100))
model.add(Dense(len(tokenizer.word_index)+1, activation='softmax'))

In [162]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [163]:
model.fit(x,y, epochs = 1500)

Epoch 1/1500


15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.0191 - loss: 5.3303
Epoch 2/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0373 - loss: 5.2771
Epoch 3/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0542 - loss: 4.9810
Epoch 4/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0467 - loss: 4.9639
Epoch 5/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0303 - loss: 4.9611
Epoch 6/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0360 - loss: 4.8763
Epoch 7/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0138 - loss: 4.9087   
Epoch 8/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0257 - loss: 4.9886   
Epoch 9/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0374 - loss: 4.8754
Epoch 10/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0304 - loss: 4.8966   
Epoch 11/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0329 - loss: 4.9139
Epoch 12/1500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - a

In [174]:
import numpy as np
text = "for i in range("


In [175]:
for i in range(5):
  token_text = tokenizer.texts_to_sequences([text])[0]
  token_text = pad_sequences([token_text], maxlen = max_lenghth, padding = 'pre')
  prob = model.predict(token_text)
  pos = np.argmax(prob)
  for word, index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
for i in range( 5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
for i in range( 5 enumerate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
for i in range( 5 enumerate fruits
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
for i in range( 5 enumerate fruits sqrt
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
for i in range( 5 enumerate fruits sqrt 25
